### ISSUE TITLE
Issue finding minecraft folder

### ISSUE THREAD

**Issue by NexieCSGO** [UnknownDetectionParty/UDP-Java#2]
it seems theres something in the MappingGen.java

Error: "Could not locate game jar for '1.12.2' in '/Users/Nexie/Library/Application Supportminecraft/versions/1.12.2/1.12.2.jar'
Run the version in your minecraft launcher and try again."

Something missing in the OS X .minecraft path?

**Comment by NexieCSGO** [comment]
fixed:
changed IOUtil.java line 154 from:
workingDirectory = new File(userHome, "Library/Application Support" + "minecraft");
to
workingDirectory = new File(userHome, "Library/Application Support/" + "minecraft");

**Comment by GenericException** [comment]
I see you closed this already but the issue is kinda obvious here. 

`/Application Supportminecraft/` should be `/Application Support/minecraft/`. The provided code works on windows, but I'm not sure why it messed up here for you. If you resolved this yourself sharing the fix would be appreciated for other users who may also encounter the bug.
